<a href="https://colab.research.google.com/github/Srikar-sri1722/JALA-ACADEMY/blob/main/Assingment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#BASIC ARRAY OPERATIONS

### 1. Create a 3x3 array filled with random integers and calculate sum, mean, and standard deviation.

In [ ]:
array_3x3 = np.random.randint(0, 11, size=(3, 3))
print("3x3 Array:\n", array_3x3)
array_sum = np.sum(array_3x3)
print("Sum of the array:", array_sum)
array_mean = np.mean(array_3x3)
print("Mean of the array:", array_mean)
array_std = np.std(array_3x3)
print("Standard deviation of the array:", array_std)

3x3 Array:
 [[7 2 5]
 [1 6 7]
 [9 2 7]]
Sum of the array: 46
Mean of the array: 5.111111111111111
Standard deviation of the array: 2.6434171674156266


### 2. Create a 1D array of 10 elements and compute the cumulative sum.

In [ ]:
array_1d = np.random.randint(1, 20, size=10)
print("1D Array:", array_1d)
cumulative_sum = np.cumsum(array_1d)
print("Cumulative Sum:", cumulative_sum)

1D Array: [ 7  5  2 12  7 15  8 10 18  1]
Cumulative Sum: [ 7 12 14 26 33 48 56 66 84 85]


### 3. Generate two 2x3 arrays with random integers and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
array_a = np.random.randint(1, 10, size=(2, 3))
array_b = np.random.randint(1, 10, size=(2, 3))
print("Array A:\n", array_a)
print("Array B:\n", array_b)
addition_result = array_a + array_b
print("Addition:\n", addition_result)
subtraction_result = array_a - array_b
print("Subtraction:\n", subtraction_result)
multiplication_result = array_a * array_b
print("Multiplication:\n", multiplication_result)
division_result = array_a / array_b
print("Division:\n", division_result)

Array A:
 [[2 3 4]
 [3 7 4]]
Array B:
 [[9 2 3]
 [5 9 4]]
Addition:
 [[11  5  7]
 [ 8 16  8]]
Subtraction:
 [[-7  1  1]
 [-2 -2  0]]
Multiplication:
 [[18  6 12]
 [15 63 16]]
Division:
 [[0.22222222 1.5        1.33333333]
 [0.6        0.77777778 1.        ]]


### 4. Create a 4x4 identity matrix.

In [ ]:
identity_matrix = np.eye(4)
print("4x4 Identity Matrix:\n", identity_matrix)

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 5. Given an array `a = np.array([5, 10, 15, 20, 25])`, divide each element by 5 using broadcasting.

In [ ]:
a = np.array([5, 10, 15, 20, 25])
print("Original Array 'a':", a)
divided_array = a / 5
print("Array 'a' divided by 5:", divided_array)

Original Array 'a': [ 5 10 15 20 25]
Array 'a' divided by 5: [1. 2. 3. 4. 5.]


# ARRAY MANIPULATIONS

### 6. Reshape a 1D array of 12 elements into a 3x4 matrix.

In [ ]:
array_1d_12 = np.arange(12)
print("Original 1D Array:", array_1d_12)
reshaped_array = array_1d_12.reshape(3, 4)
print("Reshaped 3x4 Matrix:\n", reshaped_array)

Original 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 7. Flatten a 3x3 matrix into a 1D array.

In [ ]:
matrix_3x3 = np.random.randint(1, 10, size=(3, 3))
print("Original 3x3 Matrix:\n", matrix_3x3)
flattened_array = matrix_3x3.flatten()
print("Flattened 1D Array:", flattened_array)

Original 3x3 Matrix:
 [[6 2 9]
 [8 8 5]
 [9 7 9]]
Flattened 1D Array: [6 2 9 8 8 5 9 7 9]


### 8. Stack two 3x3 matrices horizontally and vertically.

In [ ]:
matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(5, 10, size=(3, 3))
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
h_stack = np.hstack((matrix1, matrix2))
print("Horizontal Stack (hstack):\n", h_stack)
v_stack = np.vstack((matrix1, matrix2))
print("Vertical Stack (vstack):\n", v_stack)

Matrix 1:
 [[1 4 1]
 [5 5 1]
 [4 5 3]]
Matrix 2:
 [[5 7 8]
 [5 6 8]
 [8 9 7]]
Horizontal Stack (hstack):
 [[1 4 1 5 7 8]
 [5 5 1 5 6 8]
 [4 5 3 8 9 7]]
Vertical Stack (vstack):
 [[1 4 1]
 [5 5 1]
 [4 5 3]
 [5 7 8]
 [5 6 8]
 [8 9 7]]


### 9. Concatenate two arrays of different sizes along a new axis.

In [ ]:
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6, 7]])
print("Array A:\n", array_a)
print("Array B:\n", array_b)
array_c = np.array([10, 20, 30])
array_d = np.array([40, 50, 60])
print("Array C:", array_c)
print("Array D:", array_d)
concatenated_rows = np.stack((array_c, array_d), axis=0)
print("Concatenated along new axis (rows):\n", concatenated_rows)
concatenated_columns = np.stack((array_c, array_d), axis=1)
print("Concatenated along new axis (columns):\n", concatenated_columns)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6 7]]
Array C: [10 20 30]
Array D: [40 50 60]
Concatenated along new axis (rows):
 [[10 20 30]
 [40 50 60]]
Concatenated along new axis (columns):
 [[10 40]
 [20 50]
 [30 60]]


### 10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.

In [ ]:
matrix_3x2 = np.array([[1, 2], [3, 4], [5, 6]])
print("Original 3x2 Matrix:\n", matrix_3x2)
transposed_matrix = np.transpose(matrix_3x2)
print("Transposed Matrix (2x3):\n", transposed_matrix)
reshaped_back_to_3x2 = transposed_matrix.reshape(3, 2)
print("Reshaped back to 3x2 (from transposed):\n", reshaped_back_to_3x2)

Original 3x2 Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Matrix (2x3):
 [[1 3 5]
 [2 4 6]]
Reshaped back to 3x2 (from transposed):
 [[1 3]
 [5 2]
 [4 6]]


#INDEXING AND SLICING

### 11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.

In [ ]:
array_1d_15 = np.arange(15)
print("Original 1D Array (15 elements):", array_1d_15)
extracted_elements = array_1d_15[2:11:2]
print("Elements from position 2 to 10 with step 2:", extracted_elements)

Original 1D Array (15 elements): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Elements from position 2 to 10 with step 2: [ 2  4  6  8 10]


### 12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and columns 2 to 4.

In [ ]:
matrix_5x5 = np.arange(25).reshape(5, 5)
print("Original 5x5 Matrix:\n", matrix_5x5)
sub_matrix = matrix_5x5[1:4, 2:5]
print("Extracted Sub-matrix (rows 1-3, columns 2-4):\n", sub_matrix)

Original 5x5 Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Extracted Sub-matrix (rows 1-3, columns 2-4):
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


### 13. Replace all elements in a 1D array greater than 10 with the value 10.

In [ ]:
original_array = np.array([5, 12, 8, 15, 3, 20, 10, 7])
print("Original Array:", original_array)
original_array[original_array > 10] = 10
print("Array with elements > 10 replaced by 10:", original_array)

Original Array: [ 5 12  8 15  3 20 10  7]
Array with elements > 10 replaced by 10: [ 5 10  8 10  3 10 10  7]


### 14. Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].

In [ ]:
fancy_array = np.arange(10, 20)
print("Original 1D Array:", fancy_array)
indices = [0, 2, 4, 6]
selected_elements = fancy_array[indices]
print("Elements selected using fancy indexing (positions 0, 2, 4, 6):", selected_elements)

Original 1D Array: [10 11 12 13 14 15 16 17 18 19]
Elements selected using fancy indexing (positions 0, 2, 4, 6): [10 12 14 16]


### 15. Create a 1D array of 10 elements and reverse it using slicing.

In [ ]:
array_to_reverse = np.arange(0, 10)
print("Original 1D Array:", array_to_reverse)
reversed_array = array_to_reverse[::-1]
print("Reversed Array (using slicing):", reversed_array)

Original 1D Array: [0 1 2 3 4 5 6 7 8 9]
Reversed Array (using slicing): [9 8 7 6 5 4 3 2 1 0]


# BROADCASTING

### 16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.

In [ ]:
matrix_3x3_b = np.arange(1, 10).reshape(3, 3)
array_1x3 = np.array([10, 20, 30])
print("Original 3x3 Matrix:\n", matrix_3x3_b)
print("\n1x3 Array to add:\n", array_1x3)
result_add_row = matrix_3x3_b + array_1x3
print("\nResult after adding 1x3 array to each row:\n", result_add_row)

Original 3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1x3 Array to add:
 [10 20 30]

Result after adding 1x3 array to each row:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### 17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.

In [ ]:
array_1d_5 = np.array([1, 2, 3, 4, 5])
scalar_value = 10
print("Original 1D Array (5 elements):", array_1d_5)
print("Scalar Value:", scalar_value)
result_scalar_mult = array_1d_5 * scalar_value
print("Result after multiplying by scalar:\n", result_scalar_mult)

Original 1D Array (5 elements): [1 2 3 4 5]
Scalar Value: 10
Result after multiplying by scalar:
 [10 20 30 40 50]


### 18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.

In [ ]:
matrix_3x3_sub = np.arange(10, 19).reshape(3, 3)
column_vector_3x1 = np.array([[1], [2], [3]])
print("Original 3x3 Matrix:\n", matrix_3x3_sub)
print("3x1 Column Vector to subtract:\n", column_vector_3x1)
result_col_vec_sub = matrix_3x3_sub - column_vector_3x1
print("Result after subtracting column vector:\n", result_col_vec_sub)

Original 3x3 Matrix:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
3x1 Column Vector to subtract:
 [[1]
 [2]
 [3]]
Result after subtracting column vector:
 [[ 9 10 11]
 [11 12 13]
 [13 14 15]]


### 19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.

In [ ]:
arr = np.arange(24).reshape(2, 3, 4)
result = arr + 100
print("Original Array :\n",arr)
print("\nResult Array:\n",result)

Original Array :
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Result Array:
 [[[100 101 102 103]
  [104 105 106 107]
  [108 109 110 111]]

 [[112 113 114 115]
  [116 117 118 119]
  [120 121 122 123]]]


### 20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.

In [ ]:
array_4x1 = np.arange(4).reshape(4, 1)
array_1x5 = np.arange(5).reshape(1, 5)
print("Array of shape (4, 1):\n", array_4x1)
print("Array of shape (1, 5):\n", array_1x5)
result_broadcast_add = array_4x1 + array_1x5
print("Result after broadcasting addition (expected shape (4, 5)):\n", result_broadcast_add)

Array of shape (4, 1):
 [[0]
 [1]
 [2]
 [3]]
Array of shape (1, 5):
 [[0 1 2 3 4]]
Result after broadcasting addition (expected shape (4, 5)):
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


# VECTORIZED OPERATIONS

### 21. Compute the square root of each element in a 2D array using vectorized operations.

In [ ]:
array_2d = np.array([[1, 4, 9], [16, 25, 36], [49, 64, 81]])
print("Original 2D Array:\n", array_2d)
sqrt_array = np.sqrt(array_2d)
print("Square root of each element:\n", sqrt_array)

Original 2D Array:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Square root of each element:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### 22. Calculate the dot product of two 1D arrays of size 5.

In [ ]:
array_a_dot = np.array([1, 2, 3, 4, 5])
array_b_dot = np.array([6, 7, 8, 9, 10])
print("Array A:", array_a_dot)
print("Array B:", array_b_dot)
dot_product = np.dot(array_a_dot, array_b_dot)
print("Dot product:", dot_product)

Array A: [1 2 3 4 5]
Array B: [ 6  7  8  9 10]
Dot product: 130


### 23. Perform element-wise comparison of two 1D arrays and return an array of boolean values indicating where the first array has larger elements.

In [ ]:
array_compare_1 = np.array([10, 20, 5, 30, 15])
array_compare_2 = np.array([5, 25, 5, 10, 15])
print("Array 1:", array_compare_1)
print("Array 2:", array_compare_2)
comparison_result = array_compare_1 == array_compare_2
print("Comparison (Array 1 > Array 2):", comparison_result)

Array 1: [10 20  5 30 15]
Array 2: [ 5 25  5 10 15]
Comparison (Array 1 > Array 2): [False False  True False  True]


### 24. Create a 2D array and apply a vectorized operation to double the value of each element.

In [ ]:
array_double = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D Array:\n", array_double)
doubled_array = array_double * 2
print("Doubled Array:\n", doubled_array)

Original 2D Array:
 [[1 2 3]
 [4 5 6]]
Doubled Array:
 [[ 2  4  6]
 [ 8 10 12]]


### 25. Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations.

In [ ]:
random_array = np.random.randint(0, 101, size=100)
even_numbers = random_array[random_array % 2 == 0]
sum_of_even = np.sum(even_numbers)
print("Sum of all even numbers:", sum_of_even)

Sum of all even numbers: 1584


# LINEAR ALGEBRA

### 26. Create a 3x3 matrix and find its determinant.

In [ ]:
matrix_3x3_det = np.random.randint(1, 10, size=(3, 3))
print("Original 3x3 Matrix:\n", matrix_3x3_det)
determinant = np.linalg.det(matrix_3x3_det)
print("Determinant of the matrix:", determinant)

Original 3x3 Matrix:
 [[9 5 4]
 [2 1 2]
 [1 7 3]]
Determinant of the matrix: -67.00000000000004


### 27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.

In [ ]:
matrix_2x2_inv = np.array([[4, 7], [2, 6]])
print("Original 2x2 Matrix:\n", matrix_2x2_inv)
inverse_matrix = np.linalg.inv(matrix_2x2_inv)
print("Inverse Matrix:\n", inverse_matrix)
identity_check = matrix_2x2_inv @ inverse_matrix
print("Original x Inverse:\n",identity_check)

Original 2x2 Matrix:
 [[4 7]
 [2 6]]
Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Original x Inverse:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### 28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.

In [ ]:
matrix_2x2_eig = np.array([[2, 1], [1, 2]])
print("Original 2x2 Matrix:\n", matrix_2x2_eig)
eigenvalues, eigenvectors = np.linalg.eig(matrix_2x2_eig)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Original 2x2 Matrix:
 [[2 1]
 [1 2]]
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


### 29. Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.

In [ ]:
import numpy as np
A = np.array([[2, 7],[4, 6]])
B = np.array([5, 10])
try:
    solution = np.linalg.solve(A, B)
    print(solution)
except:
    print("No unique solution")

[2.5 0. ]


### 30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original matrix using the SVD components.

In [ ]:
matrix_svd = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 3x3 Matrix for SVD:\n", matrix_svd)
U, s, Vh = np.linalg.svd(matrix_svd)
print("\n U (left singular vectors):\n", U)
print("\n s (singular values):", s)
print("\n Vh (right singular vectors transposed):\n", Vh)
Sigma = np.diag(s)
reconstructed_matrix = U @ Sigma @ Vh
print("\n Reconstructed Matrix:\n", reconstructed_matrix)
print("Is reconstructed matrix close to original:", np.allclose(matrix_svd, reconstructed_matrix))

Original 3x3 Matrix for SVD:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 U (left singular vectors):
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

 s (singular values): [1.68481034e+01 1.06836951e+00 4.41842475e-16]

 Vh (right singular vectors transposed):
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]

 Reconstructed Matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Is reconstructed matrix close to original: True
